### ISSUE TITLE
Add new contributor

### ISSUE THREAD

**Issue by hsoft** [hsoft/moneyguru#425]
moneyGuru has currently only one maintainer, me. This is a dangerous situation that needs to be
corrected.

The goal is to eventually have another active maintainer, but before we can get there, the project
needs more contributors.

Whatever your skills, if you are remotely interestested in being a contributor, I'm interested in
mentoring you. I've been saying so in the [Contribute](http://hardcoded.net/moneyguru/help/en/contribute.html) page for a while, but now I'm thinking it might be a better idea to adverstise the need for contributors in a ticket. This way, it's clear whether someone has answered the call or not.

So, if you would like to start contributing to dupeGuru but would like some guidance/mentorship, simply add a comment here, we'll get started.

**Comment by ancientHacker** [comment]
Hi Virgil, I'm a long-time user (and lover) of MoneyGuru, and I'm just realizing now that you have taken it open-source.  There have a long been a few places where I would have like the ability to contribute functionality, and I would certainly hate to see support stop, so I am very motivated to be a contributor and (eventually) maintainer.  Sadly, my full-time commercial developer gig does not leave me a lot of time for open-source work, so I can't guarantee that I will be _able_ to help as much as I would _like_ to help.  But at least I'm a long-time Python dev who is very familiar with Cocoa programming, so that's a start.  And I've just forked the repo and will try building it over the weekend.  Drop me a line when you get a chance and let me know if there's any sort of immigration exercise you'd like me to try. -dan

**Comment by hsoft** [comment]
Awesome! I'll let you get started with your dev environment and all, but don't hesitate to poke me if you're stuck.

As for beginner issues, I've started using milestones to categorize the issues. Bugs marked for the 2.9 milestone seem like good introductory tasks to me. But otherwise, don't hesitate to follow your own interests in choosing an issue to work on. I'll be glad to guide you in your exploration of the code.

**Comment by ancientHacker** [comment]
So I'm a little stuck on this prerequisite: "Mac OS X: The last XCode to have the 10.7 SDK included.".  The last XCode to have the 10.7 SDK was XCode 5.1.1 which can not be installed on anything later than OS X 10.8 (Mountain Lion).  These days my main machine is a clean-installed 10.11 (El Capitan).  Any advice about getting the 10.7 SDK to be available on 10.11?

I tried just doing the build on my 10.11 machine, and it looks like the executables are built with more info in their name than the scripts expect.  I get this error sequence:

    clang -bundle -undefined dynamic_lookup -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk build/temp.macosx-10.11-x86_64-3.5/cocoalib/cocoa/CocoaProxy.o build/temp.macosx-10.11-x86_64-3.5/build/CocoaProxy.o build/temp.macosx-10.11-x86_64-3.5/build/ObjP.o build/temp.macosx-10.11-x86_64-3.5/cocoalib/HSErrorReportWindow.o build/temp.macosx-10.11-x86_64-3.5/cocoa/autogen/HSErrorReportWindow_UI.o -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -o build/lib.macosx-10.11-x86_64-3.5/CocoaProxy.cpython-35m-darwin.so -framework CoreFoundation -framework Foundation -framework AppKit -framework CoreServices
    copying build/lib.macosx-10.11-x86_64-3.5/CocoaProxy.cpython-35m-darwin.so -> 
    building: <setuptools.extension.Extension('CocoaProxy') at 0x1062f1940> result: CocoaProxy.so
    Traceback (most recent call last):
      File "build.py", line 436, in <module>
        main()
      File "build.py", line 433, in main
        build_normal(ui, args.dev, not args.no_ext)
      File "build.py", line 395, in build_normal
        build_cocoa(dev)
      File "build.py", line 148, in build_cocoa
        build_cocoa_proxy_module()
      File "build.py", line 324, in build_cocoa_proxy_module
        ['cocoalib', 'cocoa/autogen']
      File "/Users/dbrotsky/src/moneyguru/hscommon/build.py", line 484, in build_cocoa_ext
        assert op.exists(fn)
    AssertionError

I can edit the build script to expect the .cpython-35m-darwin.so suffix but things just fail further down the line.  RIght now I'm installing 10.7 (Lion) on an external drive, then I will install XCode 5.1.1, then I will try to carefully upgrade the external drive to 10.8, 10.9, 10.10, installing XCode each time, to try (eventually) to get to a 10.11 install that can actually build.  But I'm open to better suggestions! :smiley:

**Comment by hsoft** [comment]
Three things are problematic here:

1. The documentation is misleading. It's not true that the 10.7 SDK is needed. It's only needed to build the public build (I've tried using a newer SDK with a 10.7 target, but it didn't run on 10.7 machines). I could build in a 10.10 with default XCode fine. I should update that.
2. I've never tried 10.11.
3. I've not tried building moneyGuru with Python 3.5 yet.

My guess would be that Python 3.5 is the problem. Something there must have changed the way that compiled extensions are named. I'll try it soon and we'll have a better idea.

**Comment by ancientHacker** [comment]
OK, good suggestion!  The build works fine with python 3.4.  It crashes immediately when you run it, mind you, but at least it builds! :smiley: Let me know if you want me to investigate the crash, or just go back to 10.10 and wait for you to get onto 10.11 and (maybe) python 3.5.

**Comment by hsoft** [comment]
My mac build machine is updating to 10.11 today, I should be able to debug this problem this evening.

**Comment by hsoft** [comment]
Why are apple update to *big*? I'm finished with OS X 10.11 update, but now I have to update XCode and my internet connection isn't very fast, so it will take a while.

But so far, I've tried building moneyGuru on 10.11 w/ XCode 6.1 and Python 3.4.3 and it runs fine.

How do you install python on your machine, homebrew?

Me, I compile from source. I'd try homebrew to see if it's the problem, but I'll wait until XCode is finished updating to try that first.

**Comment by hsoft** [comment]
I doubt that you're on homebrew for your 3.4 install: homebrew, it turns out, only has 3.5 available.

So, I've tried compiling with XCode 7.1, I've also tried using a pre-compiled Python 3.4.3 (the binary package that is downloaded from python.org) and moneyGuru ran well in all cases.

I could, however, reproduce the problem with Python 3.5. Unfortunately, it's not only a problem of renaming the `.so` files, because when we do that, we hit a bigger problem, [waf](https://github.com/waf-project/waf), which is used to build the cocoa part of the app, doesn't worj with Python 3.5 :( I feel like this fix for this will be rather complicated...

Do you get a crash report when you run moneyGuru?

**Comment by ancientHacker** [comment]
I installed Python 3.4.3 with pyenv, which builds it on the machine.  Because I use homebrew for most installs, there are some special "new requirements" to get pyenv builds to work in 10.11: the command that finally got me to where I could build successfully was:

    CFLAGS="-I$(brew --prefix openssl)/include -I$(xcrun --show-sdk-path)/usr/include" LDFLAGS="-L$(brew --prefix openssl)/lib" PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install -v 3.4.3

I can't attach the full crash log (no write access to this repo),  but the top few lines, which seem (to me, anyway :smiley:) to indicate a build issue, are:

    Application Specific Information:
    *** Terminating app due to uncaught exception 'PythonException', reason: '<class 'AttributeError'>: 'module' object has no attribute 'PyMoneyGuruApp''
    terminating with uncaught exception of type NSException
    abort() called

I am going to try doing a clean build with my pyenv-built Python, to see if perhaps there were dirty pieces left from my 3.5 build that are messing things up.  If I still have problems, I will then try downloading the 3.4.3 binaries from python.org.  I'm assuming I can find a set with --enable-framework turned on.

Let me know if you want me to copy/paste the full crash log.

**Comment by hsoft** [comment]
Oh, I didn't know about pyenv. I'll try it later and see if that changes anything on my side.

Otherwise, yeah, it sounds like a build issue. `PyMoneyGuruApp` is the entry point to the python side from cocoa. So something went wrong during building and the entry point isn't there.

It might not be a bad idea to do a little `git clean -fxd` and start with `./bootstrap.sh` again...

**Comment by ancientHacker** [comment]
Success!  After uninstalling pyenv and brew's python3.5, and installing python 3.4.3 from the python.org website, I was able to do a clean build and the result runs beautifully.  Phew!  So now I can finally look at one of the 2.9 issues.  More as it happens.

**Comment by ancientHacker** [comment]
So it looks like all three 2.9 issues are qt-only.  Can I build and use the QT version on Mac?   Or perhaps you can recommend a Mac issue for me to look at?  (BTW, what does the "ready" label mean?)

**Comment by hsoft** [comment]
There's a description of the "ready" status on [this wiki page](https://github.com/hsoft/moneyguru/wiki/issue-labels) but I admit that I haven't been using them very well and that it doesn't add much useful information. I think I'll be removing the label soon.

**Comment by ancientHacker** [comment]
Personally I think that's a great page and the descriptions are really clear (and helpful).  I would encourage you to keep using the labels, especially if we can get some more maintainers they will be helpful for collaboration.

**Comment by hsoft** [comment]
To be clear, I didn't mean removing labels in general. I was referring specifically to the "ready" label, which looks useful, but in practice isn't and is also hard to determine.

**Comment by ancientHacker** [comment]
Ah, yes, I agree, "ready" is always a tempting designation but in my experience the useful distinction is "assigned to someone" vs. "not". :smiley:

**Comment by hsoft** [comment]
FYI @ancientHacker : I've tried pyenv on OS X just now and yet, there were problems, but there are workarounds. I've added a note on [dupeGuru's README](https://github.com/hsoft/dupeguru#os-x-and-pyenv) about it.

Having managed to add python 3.5 support for dupeGuru's OS X build (easy: just call waf with python 2...), I'm confident that it will be rather easy for moneyGuru, but it will be a bit more complicated because of the way PSMTabBarControl is built.

**Comment by hsoft** [comment]
Obviously, you know how to find your way around a code base by yourself, I hope you'll stick around!

If you want to dive into Qt, you're of course welcome to do so, but otherwise, I'll motivate myself to get on with the two other bugs (which are qt-specific) in the release so that your fix can get released in a reasonable amount of time.

How was your code base discovery experience @ancientHacker ? Is the documentation sufficient? Is writing tests convenient enough?

**Comment by ancientHacker** [comment]
I'd actually be happy to learn about Qt interface programming, but is that supported on Mac?  Yes I work in emacs and the command line for the most part, but I've never done any actual Linux non-server work, so I have absolutely no familiarity with any of the desktop windowing systems and no particular desire to learn them.  If I could use Qt on Mac that would be fine; do you build it that way?

As to code base discovery, it's a mixed bag.  The testing system in particular feels very undocumented; I really had to just read a lot of other tests to figure out how it works, and do a lot of code groveling to figure out the difference between and entry sheet and a transaction sheet and a balance sheet and so on.  On the app side, the code with your name is on is quite well documented (for my taste); the code with other names on it (from 1997) feels less well-documented and less "of the same cloth".  But for me the biggest issue is code readability, and all the code is quite readable.  I love that your style is not terse; especially that you tend to assign useful sub-expressions to variables rather than just using them in a huge expression.  I find that makes it quite easy to see what the conceptual structure of the code is.

And yes, I'm not going anywhere :).

**Comment by hsoft** [comment]
It's been a while since I've done it, but yes moneyGuru can be ran under Qt on a Mac. It's only a matter of having PyQt installed and using `--ui=qt` with configure.py.

Code from 1997? Which code is that?

Thanks for the feedback about the test code, I'll try to document it (especially the terminology, which changed over time in the UI, but not in the code, which is the source of the confusion).

**Comment by ancientHacker** [comment]
OK so I have built successfully under QtPy on Mac.  So when I have a chance I'll start looking at the QT bugs.

Sorry, I meant 2007, not 1997, and it's the code by Eric McSween that I find less readable than yours.

**Comment by codeclog** [comment]
Hi Virgil and Daniel,

Been following this git for a while and really like what you are doing. 

I am interested in contributing to this development for Mac OS X. As of right now, I tried cloning and successfully building the latest codebase (El Capitan - 10.11 using Python 3.5.1 using brew and virtualenv) but got stuck when trying to run it. Not sure if I did something wrong or if this only works with 3.4+ as per your above conversations. 
 
<code>$ python run.py</code><BR>
<code>LSOpenURLsWithRole() failed with error -10810 for the file /Users/cd/Code/py/mg_p3/build/moneyGuru.app.
</code><BR>

I will try digging further but feel free to shout out if you think I am trekking down the wrong path.

**Comment by hsoft** [comment]
Hi @codeclog , welcome aboard! I don't know what this error means, but I can give you clues to have more information. Two things to try:

1. Look at `python build.py`'s output. Any buried error message in there?
2. Try calling the executable directly: `./build/moneyGuru.app/Contents/MacOS/moneyGuru` (or something close, my Mac is shut down right now, too lazy to verify the path).

**Comment by codeclog** [comment]
Thanks Virgil!

Other than a few warnings thrown by the PSM components for deprecated functions, the build went through all the way with no breaks. I have XCode 7.2. Sometimes having the latest and greatest isnt good! ;)

I did try calling the executable directly but that didnt help. Let me try cleaning up and re-building...

**Comment by ancientHacker** [comment]
So this report caused me to get the latest sources and build them on my machine.  Unlike Collin, I use pyenv to install and run my pythons, so I am not running the brew python but "stock" python 3.5.1.  But like Collin, I also get a crash as soon as I run python build.py (or run the executable directly).  In my case the crash log is:
````
AttributeError: module '__main__' has no attribute 'PyMoneyGuruApp'
2016-01-04 00:07:14.454 moneyGuru[90021:287763] An uncaught exception was raised
2016-01-04 00:07:14.454 moneyGuru[90021:287763] <class 'AttributeError'>: module '__main__' has no attribute 'PyMoneyGuruApp'
````
Interestingly, however, when I run the executable from the command line I see this right before the crash:

    ImportError: No module named 'math'

Back to you, Virgil! :)

**Comment by hsoft** [comment]
@ancientHacker I also got an error when trying a freshly installed v3.5.1 with pyenv, but that was because 3.5.1 (and not 3.5.0) isn't built with the `-framework` option, which moneyGuru needs for embedding Python into itself.

I've just pushed a change that makes build fail more gracefully when this is the case. Can you check that you get that new error? @codeclog can you also try again please?

**Comment by ancientHacker** [comment]
@hsoft Do you mean the --enable-framework Python configure option?  In fact I did use this when installing 3.5.1:

    env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.5.1

Failure to specify this keeps the build from succeeding, because without it there is no libPython.m available in the right location.

In any event I will pull down your latest change and do a clean build to see what happens. -d.

**Comment by hsoft** [comment]
Oh, sorry, I forgot about that flag, which you already mention earlier.

I've re-installed v3.5.1 with `env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.5.1`, but now moneyGuru builds and runs properly, which doesn't help us solve our problem...

I'll try updating XCode to the latest version.

**Comment by ancientHacker** [comment]
Sigh.  Without pulling down the latest change, I just completely uninstalled pyenv, then reinstalled it, then installed python 3.5.1 (with --enable-framework), then did a completely clean build of moneyguru, and... it runs like a champ!  This makes me suspect that I had corrupt build stuff sitting somewhere the last time I built and it failed, even though I would have sworn that I had done a clean build.  This is the kind of thing that makes me hate computers...

The only thing I did in a different way *intentionally* this time over last time was something that *should* make no difference: I did
```
pyenv global 3.5.1
pyvenv --system-site-packages env
```
rather than
```
pyenv local 3.5.1
pyvenv --system-site-packages env
```
Now, because things worked better this time, I will have to what I did last time just to _verify_ that it has no effect.  Sigh.

**Comment by codeclog** [comment]
Awesome! Let me try it this evening. I use virtualenv though most of the time. Let me give pyenv a shot and see how it goes. Will let you know. 

BTW... you can call me, Collin :)

**Comment by codeclog** [comment]
Alas! ... build complete in 58 seconds ... and app runs great with pyenv! Not with brew/virtualenv though :(

Thanks Dan for the brew uninstall tip! :)

**Comment by HarisHashim** [comment]
I am interested for the window maintainer if that is still open!

**Comment by hsoft** [comment]
Hi @HarisHashim. Yes, that's still open. So do you have the means and the will to create windows builds for new moneyGuru releases and take care of windows-related issues?

I'll gladly guide you through this, but my ability to help you are limited since I don't have a windows machine set up for building moneyGuru myself.

Your first challenge will be to find a way to replace the old way to generate the installer, because it's currently based on a proprietary software called [Advanced Installer](http://www.advancedinstaller.com/) for which I bought a license ages ago and never replaced myself. You'll have to replace that part with something else.

**Comment by wolfpackmars2** [comment]
[NSIS](http://nsis.sourceforge.net/Main_Page) or [InnoSetup](https://en.wikipedia.org/wiki/Inno_Setup) are two options.

InnoSetup was the solution I've used in the past, and I remember it being very easy to learn and use.  Admittedly, it's been some time since I've used it.

**Comment by haris-hashim** [comment]
Hello @hsoft  & @wolfpackmars2 

This is the same account as the other same sounding name account. I was not active using that one and miss your earlier tag.

I will have a look into installer requirement when my time is a little bit less insane and will get back to you guys here before creating new discussion specific to Windows installer.

**Comment by aeroaks** [comment]
@hsoft I would like to contribute and learn. I am currently professionally involved with python and qt4 based development on windows and can definitely learn a lot by working in this project.

**Comment by hsoft** [comment]
@aeroaks good! Your first step would be to set yourself a development environment, and then tackle an issue you'd like to solve. I'll be happy to assist if you're stuck or if the documentation is inadequate.

**Comment by hsoft** [comment]
moneyGuru is now unmaintained: https://github.com/hsoft/moneyguru#unmaintained
